#! /bin/sh

### AUTOSTART ###
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
ibus-daemon --xim -d -r &
nitrogen --restore &
~/.config/polybar/launch.sh &

### MONITORS ###
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0

### BSPWM SETTINGS ###
bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focs true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true


### BSPWM COLORS ###
# TODO
