config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_alacritty_config:
    src: alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_i3_config:
    src: i3/config
    dst: ~/.config/i3/config
  f_i3blocks_config:
    src: i3blocks/config
    dst: ~/.config/i3blocks/config
  f_rofi_config:
    src: rofi/menu.rasi
    dst: ~/.config/rofi/menu.rasi
  d_functions:
    src: fish/functions
    dst: ~/.config/fish/functions
  f_fish_config:
    src: fish/config.fish
    dst: ~/.config/fish/config.fish
  f_bspwmrc:
    src: bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
  f_sxhkdrc:
    src: sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_picom:
    src: picom/picom.conf
    dst: ~/.config/picom/picom.conf
  d_polybar:
    src: polybar
    dst: ~/.config/polybar
  d_scripts:
    src: scripts
    dst: ~/.scripts
profiles:
  home:
    dotfiles:
    - f_alacritty_config
    - f_i3_config
    - f_i3blocks_config
    - f_rofi_config
    - d_functions
    - f_fish_config
    - f_bspwmrc
    - f_sxhkdrc
    - f_picom
    - d_polybar
    - d_scripts
